language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install coveralls
  - pip install codecov
  - pip install vcrpy
  - pip install -r requirements.txt
  - python setup.py install
script:
  - coverage run --source nasapy -m py.test
  - coverage report
after_success:
  - coveralls
  - codecov